# Generated by Django 4.0.6 on 2022-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='note',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
