# Generated by Django 4.0.6 on 2022-08-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='note',
            field=models.TextField(max_length=100),
        ),
    ]
