# Generated by Django 4.0.6 on 2022-09-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employeeattendance_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='note',
        ),
    ]
