# Generated by Django 4.0.6 on 2022-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_employeeattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
