# Generated by Django 4.0.6 on 2022-09-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_employeeattendance_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together=set(),
        ),
    ]
