# Generated by Django 4.0.6 on 2022-09-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('attendance', '0004_alter_employeeattendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'date')},
        ),
    ]
