# Generated by Django 4.0.6 on 2022-08-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
