# Generated by Django 4.0.6 on 2022-09-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('attendance', '0006_rename_employee_id_employeeattendance_employee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'date')},
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='note',
        ),
    ]
