# Generated by Django 4.0.6 on 2022-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('street_line2', models.CharField(blank=True, max_length=100, verbose_name='Address 2')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='ZIP code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
